import yaml

# Emulate a user configuring the module.
module_config = dict()
with open(workflow.source_path("../../config/config.yaml"), "r") as f:
    module_config["module_euro_gas_grid"] = yaml.safe_load(f.read())

# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `config:` specifies the module configuration.
# `pathvars:` helps you re-wire where the module places files.
module module_euro_gas_grid:
    snakefile:
        "../../workflow/Snakefile"
    config:
        module_config["module_euro_gas_grid"]
    pathvars:
        # Redirect specific user resources (inputs)
        user_shapes="resources/inputs/{shapes}/shapes.parquet",
        # Redirect specific module results (outputs)
        hubs="results/outputs/{shapes}/hubs.parquet",
        nodes="results/outputs/{shapes}/nodes.parquet",
        pipelines="results/outputs/{shapes}/pipelines.parquet",
        salt_cavern_h2_potential="results/outputs/{shapes}/salt_cavern_h2_potential.parquet",
        # Redirect module intermediate files
        logs="resources/euro_gas_grid/logs",
        resources="resources/euro_gas_grid/resources",
        results="resources/euro_gas_grid/results",


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_euro_gas_grid as module_euro_gas_grid_*


FILES = ["hubs", "nodes", "pipelines", "salt_cavern_h2_potential"]


# Request something from the module
rule all:
    message:
        "A generic test case for your module."
    default_target: True
    input:
        expand(
            "results/outputs/BALK/{file}.parquet",
            file=FILES,
        ),
