# Module settings that users cannot modify.
resources:
  automatic:
    # Links for automatically downloaded files
    scigrid_gas: https://zenodo.org/records/5079748/files/IGGIELGNC.zip
    salt_cavern_h2: https://zenodo.org/records/18153129/files/h2_salt_cavern_storage.parquet
    natural_earth:
      countries: "https://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_0_countries.zip"
