# A minimal example of how to configure thi
resolution: national #national, e_highways

crs:
  projected: "EPSG:3857"

add_north_sea: True

clustering:
  method: "node-relevance"  # options: node-relevance, max-transfer
  min_segment_length: 1000  # matches projected CRS unit (m)
  replace_sovereign:
    NL1: NLD
    FI1: FIN
    GB1: GBR
    DN1: DNK


imputation:
  buffer_distance: 100
  inferred_mm: 500
  recalculate_below_mw: 500
  ch4_to_h2_ratio: 0.8
  length_factor: 1.25
