# A minimal example of how to configure thi
resolution: national #national, e_highways

crs:
  projected: "EPSG:3857"

plots:
  facecolor: 'white'
  edgecolor: "#c2c2c0"
  linewidth: 0.5
  cmap: winter_r

